#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    theme=$1
else
    theme=$(find ~/.config/alacritty/themes/themes -type f -name "*.toml" | sed 's#.*/##' | fzf -x --scheme path --border bottom --border-label "Choose theme for alacritty" --ansi)
fi

if [[ -z $theme ]]; then
    exit 0
fi

alacritty_file=~/.config/alacritty/alacritty.toml
alacritty_file_new=$alacritty_file.new
alacritty_theme="import = [ '~/.config/alacritty/themes/themes/$theme' ]"

touch $alacritty_file_new
echo $alacritty_theme >> $alacritty_file_new
sed '1d' $alacritty_file >> $alacritty_file_new

rm $alacritty_file
mv $alacritty_file_new $alacritty_file

echo "set alacritty theme to: $theme"
