#!/usr/bin/env bash

curr_dir=$(pwd)

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find $curr_dir -mindepth 1 -maxdepth 3 -type d | fzf -x --scheme path --border bottom --border-label "Open directory" --ansi --color="fg:#c0caf5,hl:#bb9af7" --color="fg+:#c0caf5,hl+:#7dcfff" --color=info:"#7aa2f7,prompt:#7dcfff,pointer:#7dcfff" --color="marker:#9ece6a,spinner:#9ece6a,header:#9ece6a")
fi

if [[ -z $selected ]]; then
    exit 0
fi

cd $selected
$SHELL
